---
- name: install docker deps
  apt:
    pkg: "{{ pkg_item }}"
    state: installed
    update_cache: no
    install_recommends: no
  with_items: '{{ docker_deps }}'
  loop_control:
    loop_var: pkg_item

- name: add repository key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution }}/gpg
    id: 0EBFCD88

- name: add repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution }} {{ ansible_lsb.codename }} stable
  notify: update apt caches

- meta: flush_handlers

- name: install docker
  apt:
    pkg: docker-ce
    state: installed
    update_cache: no
    install_recommends: yes
  notify: restart docker
