- name: create systemd configuration directory for proxy
  when: docker_proxy is defined and docker_proxy
  file:
    path: /etc/system.d/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: configure proxy
  when: docker_proxy is defined and docker_proxy
  template:
    src: etc/system.d/system/docker.service.d/http-proxy.conf.j2
    dest: /etc/system.d/system/docker.service.d/http-proxy.conf
    owner: root
    group: root
    mode: 0644
  notify: systemd daemon-reload
